FROM hariszaf/pemabase:v.2.0.1
MAINTAINER Haris Zafeiropoulos haris-zaf@hcmr.gr

# Copy and paste the manually written scripts that PEMA needs
WORKDIR /home/scripts
COPY /scripts/ ./
RUN chmod -R +777 /home/scripts

# Copy and paste the PEMA script!
WORKDIR /home
COPY pema_latest.bds .

## make a source of the .bashrc file
WORKDIR /root

RUN ["/bin/bash", "-c", "-l",  "source /root/.bashrc"]

RUN export PATH=$PATH:/home/tools/BDS/.bds
ENV PATH=$PATH:/home/tools/BDS/.bds

RUN pip3 uninstall -y cutadapt
#RUN apt install python3-cutadapt


WORKDIR /home
RUN curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh &&\
	 bash Miniconda3-latest-Linux-x86_64.sh -b -p "/home/miniconda3"

RUN ./miniconda3/bin/conda config --add channels bioconda 
RUN ./miniconda3/bin/conda config --add channels conda-forge
RUN ./miniconda3/bin/conda install -c bioconda cutadapt





# Set "home" as my working directory when a container starts
WORKDIR /home
